### PR TITLE
Add support for Scala 2.13

### PR DESCRIPTION
**Pull request by marko-asplund**

### CODE REVIEW

**Comment by marko-asplund** [comment]
Build for the latest commit in this branch seems to be passing in Travis though this is not reflected in the PR build status:
https://travis-ci.org/github/NthPortal/extra-predef/builds/723866404

**Comment by marko-asplund** [comment]
@NthPortal PR ready for review 🙏

**Review by NthPortal — APPROVED** [review]
Thanks so much! I didn't know anyone used this 😳

IIRC, there are some things this library could do a bit more cleanly, so I'll try to give it a bit of love and polish it up soon. I'll also need to redo the build to publish automagically.

Not sure why Travis is having trouble. I'll give him a quick bounce, but if that doesn't work, I'll just force a merge without the check "officially" passing.

**Comment by NthPortal** [comment]
/nothingtoseehere
(I know this doesn't do anything in this repo, but pretend it does)

**Comment by NthPortal** [comment]
2.0.0 is on its way to Maven Central

**Comment by marko-asplund** [comment]
Awesome - thanks! 😻 
While upgrading code to Scala 2.13 I noticed extra-predef is being used through versions 😄 .
Thanks for the great work on both of these! 👍

**Pull request merged**
